### ISSUE TITLE
Q3 Epic Tracker

### ISSUE THREAD

**Issue by jmcook1186** [ethereum/geth-website#1]
## Overview 

This repository is a temporary home for the new Geth website while it is in development. 
Project management notes are available on the EF Q3 Sprint planning Notion [here](https://www.notion.so/efdn/Build-new-Geth-website-bf35a46cfe5848db83ac3acb5191eb1c).

Ethereum.org team is @jmcook1186 @nloureiro @nhsz @samajammin 

The following outlines the outstanding tasks to complete for this epic:

### Project Management tasks
[Top level PM Notion](https://www.notion.so/efdn/Build-new-Geth-website-bf35a46cfe5848db83ac3acb5191eb1c)
- [ ] Scope epic [Notion](https://www.notion.so/efdn/Story-scope-epic-602468fcb16145b9952587a31150de80)
- [ ] internal kick-off meeting e.org
- [ ] kick-off meeting e.org <> geth
- [ ] get approval on content plan from geth team

### Design Tasks

- [ ] sketch out figma designs ([Notion](https://www.notion.so/efdn/Story-Geth-site-design-sketches-2b4a70adedec42ebb7b8599513266d22)
- [ ] choose final design idea
- [ ] get approval of final design from geth team

### Dev tasks
- [ ] determine downloads page strategy [Notion](https://www.notion.so/efdn/Sort-out-implementation-of-downloads-page-7fe2af211711491e8cd0b52659e12102)
- [ ] determine overall site strategy [Notion](https://www.notion.so/efdn/Story-Geth-site-define-development-plan-c5d5f312ceac4847b123b0192aa94621)
- [ ] define json-rpc api page strategy [Notion](https://www.notion.so/efdn/Story-Geth-site-define-JSON-RPC-API-plan-a4ec9bef3ed643a19e699ac5107b1e71)
- [ ] configure preview deploys for this repo
- [ ] determine search strategy [Notion](https://www.notion.so/efdn/Add-site-search-fe42d926ce8d4048b883ea25ef7ec5aa)
- [ ] define hosting/deploy [Notion](https://www.notion.so/efdn/Sort-out-hosting-deployment-e62bec37b5e6414cae689457f8c2c904)
- [ ] Build site v1!
- [ ] launch

#### initial
- [ ] draft content management plan [Notion](https://www.notion.so/efdn/Story-Geth-site-content-management-plan-e0c137f5383949a68acd7e411584351a)
- [ ] migrate material from geth.ethereum.org

#### pages
(tick when created/migrated/updated and ready for review)
[Notion](https://www.notion.so/efdn/Story-Geth-site-content-management-plan-e0c137f5383949a68acd7e411584351a)

- [ ] │   │   ├── developers
- [ ] │   │   │   ├── dapp-developer
- [ ] │   │   │   │   ├── custom-tracer.md            reviewed
- [ ] │   │   │   │   ├── mobile.md                   reviewed
- [ ] │   │   │   │   ├── native-accounts.md          reviewed
- [ ] │   │   │   │   ├── native-bindings.md          reviewed
- [ ] │   │   │   │   ├── native.md                   reviewed
- [ ] │   │   │   │   ├── tracers.md                   reviewed
- [ ] │   │   │   │   └── built-in-tracers.md         reviewed
- [ ] │   │   │   └── geth-developer               
- [ ] │   │   │       ├── code-review-guidelines.md   modified not reviewed   
- [ ] │   │   │       ├── contributing.md             modified not reviewed
- [ ] │   │   │       ├── devguide.md
- [ ] │   │   │       ├── dev-mode.md 
- [ ] │   │   │       ├── dns-discovery-setup.md
- [ ] │   │   │       ├── issue-handling-workflow.md
- [ ] │   │   │       ├── private-network.md         reviewed
- [ ] │   │   │       └── vulnerabilities.md
- [ ] │   │   ├── faq.md
- [ ] │   │   ├── fundamentals
- [ ] │   │   │   ├── Backup--restore.md             modified not reviewed
- [ ] │   │   │   ├── Command-Line-Options.md        reviewed              
- [ ] │   │   │   ├── Installing-Geth.md             reviewed
- [ ] │   │   │   ├── les.md                         reviewed
- [ ] │   │   │   ├── account-management.md          reviewed
- [ ] │   │   │   ├── node-architecture.md           modified not reviewed
- [ ] │   │   │   ├── security.md                    new page not reviewed
- [ ] |     |    |   └── peer-to-peer.md                reviewed
- [ ] │   │   ├── getting_started
- [ ] │   │   │   ├── consensus-clients.md           modified not reviewed
- [ ] │   │   │   ├── getting-started-with-clef.md   reviewed
- [ ] │   │   │   └── getting-started.md             reviewed
- [ ] │   │   │   └── Installing-Geth.md             reviewed 
- [ ] │   │   ├── interacting_with_geth
- [ ] │   │   │   ├── JavaScript-Console.md          reviewed
- [ ] │   │   │   └── RPC
- [ ] │   │   │       ├── batch.md
- [ ] │   │   │       ├── graphql.md
- [ ] │   │   │       ├── ns-admin.md
- [ ] │   │   │       ├── ns-clique.md
- [ ] │   │   │       ├── ns-debug.md
- [ ] │   │   │       ├── ns-eth.md
- [ ] │   │   │       ├── ns-les.md
- [ ] │   │   │       ├── ns-miner.md
- [ ] │   │   │       ├── ns-net.md
- [ ] │   │   │       ├── ns-personal.md
- [ ] │   │   │       ├── ns-txpool.md
- [ ] │   │   │       ├── objects.md
- [ ] │   │   │       ├── pubsub.md
- [ ] │   │   │       └── server.md
- [ ] │   │   ├── monitoring
- [ ] │   │   │   ├── dashboards.md                 new not reviewed
- [ ] │   │   │   └── metrics.md                    reviewed
- [ ] │   │   └── tools
- [ ] │   │       ├── abigen                       new not reviewed
- [ ] │   │       ├── Clef
- [ ] │   │       │   ├── apis.md
- [ ] │   │       │   ├── CliqueSigning.md
- [ ] │   │       │   ├── datatypes.md
- [ ] │   │       │   ├── Introduction.md          reviewed
- [ ] │   │       │   ├── Rules.md                 reviewed
- [ ] │   │       │   ├── Setup.md
- [ ] │   │       │   └── Tutorial.md              reviewed
- [ ] │   │       └── puppeth
- [ ] │   └── downloads.md
- [ ] │   └── homepage.md                          new not reviewed

**Comment by samajammin** [comment]
End of Q3 update:

In collaboration with the Geth team, we’ve completely redesigned, restructured, rewrote and began rebuilding a new Geth website! We expanded documentation with several new pages and brought content up to date with the latest release of the go-ethereum client. New pages explaining console logs, consensus clients, node architecture, pruning, sync modes, dashboards and tools such as `abigen` and `clef` have been added to the docs and much of the existing material has had a substantial overhaul with the aim of giving users a more complete and accessible overview of the Geth software. 

The website design has also had a complete rethink. @nloureiro generated three different concepts for the site, and after a few rounds of discussion and refinement with the Geth team we settled on a concept that pulls together a newspaper-like format with command line and retro gaming styles. It’s a striking new look for the site that aligns nicely with Geth’s role as an old-school, OG product that has led the community into the cutting-edge new proof-of-stake era.

You can get a sneak peak at the designs here: 
https://www.figma.com/file/ekzIgwyeVKLtFSAcnA0Q0D/geth-website?node-id=6%3A31

The design and content has been handed over to @nhsz and @corwintines to build. [Preview deploys of the mobile site](https://geth-website-git-homepage-mobile-ethdevops.vercel.app/) are already available for reviewing and the rest of the site is progressing quickly. We’ll finish development and ship the new site in Q4.

**Comment by samajammin** [comment]
@jmcook1186 I believe this can be closed out, ya?
